"""empty message

Revision ID: 684918e6477e
Revises: 3af751ecec93
Create Date: 2020-04-14 09:00:20.576140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684918e6477e'
down_revision = '3af751ecec93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('update todos set completed = False where completed IS NULL')

    op.alter_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
